### ISSUE TITLE
Cannot install the extension from Visual Studio Marketplace: Element not found. (Exception from HRESULT: 0x80070490)

### ISSUE THREAD

**Issue by raspiduino** [hrai/auto-save-vs-extension#18]
I tried to install this extension from the Visual Studio Marketplace, then restart VS. The VSIX launched for a while and then tell me Element not found. (Exception from HRESULT: 0x80070490).
Here is the log file:
```
2/3/2021 2:45:45 PM - Microsoft VSIX Installer
2/3/2021 2:45:45 PM - -------------------------------------------
2/3/2021 2:45:45 PM - vsixinstaller.exe version:
2/3/2021 2:45:45 PM - 16.8.3038
2/3/2021 2:45:45 PM - -------------------------------------------
2/3/2021 2:45:45 PM - Command line parameters:
2/3/2021 2:45:45 PM - D:\VisualStudio\Common7\IDE\vsixinstaller.exe,/appidinstallpath:D:\VisualStudio\Common7\IDE\devenv.exe,/skuName:Community,/skuVersion:16.8.30711.63,/appidname:Microsoft Visual Studio Community 2019,/culture:en-US,/noep,%temp%\VSIXvrkbwwbl.vsix
2/3/2021 2:45:45 PM - -------------------------------------------
2/3/2021 2:45:45 PM - Microsoft VSIX Installer
2/3/2021 2:45:45 PM - -------------------------------------------
2/3/2021 2:45:56 PM - Initializing Install...
2/3/2021 2:45:57 PM - Extension Details...
2/3/2021 2:45:57 PM - 	Identifier         : AutoSaveFile.dee600b4-1678-4538-bad2-bc1e05056118
2/3/2021 2:45:57 PM - 	Name               : Auto Save File
2/3/2021 2:45:57 PM - 	Author             : Hangjit Rai
2/3/2021 2:45:57 PM - 	Version            : 2.5
2/3/2021 2:45:57 PM - 	Description        : This extension help you to save your changes as you make them without having to type Ctrl-S. The time delay is currently set to 5 seconds. Only exception is when the last added character was period[.].

The file also gets saved if it loses focus.

The time delay can be configured from the options panel.
2/3/2021 2:45:57 PM - 	Locale             : en-US
2/3/2021 2:45:57 PM - 	MoreInfoURL        : https://github.com/hrai/auto-save-vs-extension
2/3/2021 2:45:57 PM - 	InstalledByMSI     : False
2/3/2021 2:45:57 PM - 	SupportedFrameworkVersionRange : [4.5,)
2/3/2021 2:45:57 PM - 
2/3/2021 2:45:57 PM - 	SignatureState     : Unsigned
2/3/2021 2:45:57 PM - 	Supported Products : 
2/3/2021 2:45:57 PM - 		Microsoft.VisualStudio.Community
2/3/2021 2:45:57 PM - 			Version : [16.0,17.0)
2/3/2021 2:45:57 PM - 		Microsoft.VisualStudio.Pro
2/3/2021 2:45:57 PM - 			Version : [16.0,17.0)
2/3/2021 2:45:57 PM - 		Microsoft.VisualStudio.Enterprise
2/3/2021 2:45:57 PM - 			Version : [16.0,17.0)
2/3/2021 2:45:57 PM - 
2/3/2021 2:45:57 PM - 	References         : 
2/3/2021 2:45:57 PM - 	Prerequisites      : 
2/3/2021 2:45:57 PM - 		-------------------------------------------------------
2/3/2021 2:45:57 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/3/2021 2:45:57 PM - 		Name         : Visual Studio core editor
2/3/2021 2:45:57 PM - 		Version      : [16.0,17.0)
2/3/2021 2:45:57 PM - 
2/3/2021 2:45:57 PM - Signature Details...
2/3/2021 2:45:57 PM - 	Extension is not signed.
2/3/2021 2:45:57 PM - 
2/3/2021 2:45:57 PM - System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at Microsoft.VisualStudio.Setup.Configuration.ISetupConfiguration2.GetInstanceForPath(String path)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix)
   at VSIXInstaller.LocationBasedSKU..ctor(String appidInstallPath, String appidName, Version vsVersion, String edition, String rootSuffix, IntPtr alternateUserToken)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Thanks for any help!

**Comment by hrai** [comment]
@raspiduino what version of VS are you running?

**Comment by raspiduino** [comment]
VS 2019

**Comment by hrai** [comment]
@raspiduino

I'm on 2019 as well but couldn't replicate this issue.

I found this issue. Perhaps you can try repairing your VS install and try reinstalling? 
https://github.com/tomasr/viasfora/issues/274

**Comment by raspiduino** [comment]
Probably the problem is from my VS installation. I will try installing again.
